# Generated by Django 3.1.6 on 2021-02-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blod',
            new_name='blog',
        ),
    ]
