# Generated by Django 3.1.6 on 2021-02-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210217_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
