# Generated by Django 3.1.6 on 2021-02-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_nm', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=50)),
                ('u_sub', models.CharField(max_length=50)),
                ('u_msg', models.CharField(max_length=500)),
            ],
        ),
    ]
