# Generated by Django 3.1.6 on 2021-02-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20210219_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
