# Generated by Django 3.1.6 on 2021-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dscr',
            field=models.TextField(),
        ),
    ]
